# Generated by Django 5.2.1 on 2025-06-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_question_media_url_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='players',
        ),
        migrations.RemoveField(
            model_name='player',
            name='chips',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='has_blue_chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_green_chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_red_chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_yellow_chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
