# Generated by Django 5.2.1 on 2025-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamesession_players_remove_player_chips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
