# Generated by Django 5.2.1 on 2025-06-29 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('tile_type', models.CharField(choices=[('NORMAL', 'Normal'), ('HQ', 'Headquarters'), ('ROLL_AGAIN', 'Roll Again'), ('START', 'Start')], default='NORMAL', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
            ],
        ),
    ]
