# Generated by Django 5.2.1 on 2025-07-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_position_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_player_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('session', 'session_player_id')},
        ),
    ]
