# Generated by Django 5.2.1 on 2025-07-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_session_player_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
