# Generated by Django 5.2.1 on 2025-07-19 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='index',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='tile_type',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='category_c1',
            field=models.CharField(default='C1', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='category_c2',
            field=models.CharField(default='C2', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='category_c3',
            field=models.CharField(default='C3', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='category_c4',
            field=models.CharField(default='C4', max_length=100),
        ),
        migrations.AddField(
            model_name='tile',
            name='label',
            field=models.CharField(default='C1', max_length=100),
        ),
        migrations.AddField(
            model_name='tile',
            name='neighbors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tile',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tile',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game.gamesession'),
        ),
    ]
