# Generated by Django 5.2.1 on 2025-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_tile_category_remove_tile_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='current_turn',
            field=models.IntegerField(default=1),
        ),
    ]
